---
###################################################################################################
# YouTube Content Notifications
#
# Original Repo: PinkyWafer
# https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/youtube/youtube_notifications.yaml
# YouTube Color Hex Code: #FF0000 (RED), #282828 (Almost Black)
###################################################################################################
group:
  YouTube:
    name: YouTube Channels
    icon: mdi:youtube
    entities:
      - sensor.paul_hibbert
      - sensor.drzzs
      - sensor.resinchem_tech
automation:
  - id: 'b10a4f16-765d-4f84-b13b-d80b6697db67'
    alias: Entertainment // YouTube / YouTube Notifications
    mode: queued
    trigger:
      - platform: state
        entity_id:
          - sensor.paul_hibbert
          - sensor.drzzs
          - sensor.resinchem_tech
        attribute: url
    condition:
      - condition: state
        entity_id: input_boolean.youtube_alerts
        state: 'on'
      - condition: state
        entity_id: input_boolean.sleeping
        state: 'off'        
    action:
      - service: notify.mobile_app_jrs_iphone
        data:
          message: '{{ trigger.to_state.state }}'
          title: >
            {% if trigger.to_state.attributes.live -%}
              {{trigger.to_state.attributes.friendly_name}} is Live!
            {%- else -%}
              New video from {{trigger.to_state.attributes.friendly_name}}
            {%- endif %}
#          target: !secret discord_channelid
#          data_template:
#            tag: '{{ trigger.entity_id }}'
          data:
            image: '{{ trigger.to_state.attributes.entity_picture }}'
            actions:
              - action: "URI"
                title: "Watch Now"
                uri: '{{ trigger.to_state.attributes.url }}'
# Good Working Mobile App Notification####################################
#      - service: notify.mobile_app_jrs_iphone
#        data:
#          message: '{{ trigger.to_state.state }}'
#          title: >
#            {% if trigger.to_state.attributes.live -%}
#              {{trigger.to_state.attributes.friendly_name}} is Live!
#            {%- else -%}
#              New video from {{trigger.to_state.attributes.friendly_name}}
#            {%- endif %}
#          target: !secret discord_channelid
#          data:
#            image: '{{ trigger.to_state.attributes.entity_picture }}'
#            actions:
#              - action: "URI"
#                title: "Watch Now"
#                uri: '{{ trigger.to_state.attributes.url }}'
##########################################################################
##      - service: notify.telegram_group
##        data:
##          title: '*HASS*'
##          message: Hello World 0803
          
#      - service: persistent_notification.create
#        data_template:
#          notification_id: youtube_notification
#          title: >
#            {% if trigger.to_state.attributes.live -%}
#              {{trigger.to_state.attributes.friendly_name}} is Live!
#            {%- else -%}
#              New video from {{trigger.to_state.attributes.friendly_name}}
#            {%- endif %}
#          message: '{{ trigger.to_state.state }}'