---
#########################################################################################################
# Twitch Integration
# GitHub: @waynethebrain/home-assistant-config/
# Version: 3.6522.2
# OP:https://github.com/happyleavesaoc/my-home-automation/blob/master/homeassistant/packages/twitch.yaml
# Description: Monitor Twitch streamer activity on twitch.tv.
# Notes: Twitch Purple Hex Color Code: #9146FF
# Latest Error: None - 6/5/2022 6:00PM
#########################################################################################################

sensor:
  platform: twitch
  entity_namespace: twitch
  client_id: !secret twitch_api
  client_secret: !secret twitch_api_secret
  token: !secret twitch_token
  channels:
    - drzzs
    - jfavignano
    - squirrel
    - ttthefineprinttt
group:
  Twitch Users:
    - sensor.twitch_drzzs
    - sensor.twitch_jfavignano
    - sensor.twitch_squirrel
    - input_boolean.twitch_alerts
    
input_boolean:
  twitch_alerts:
    name: Twitch Alerts
    icon: mdi:twitch
    initial: true

automation:
  # Streamer online notifications.
  - alias: Entertainment -- Twitch - Twitch User Live Notification
    id: twitch-user-streaming-automation
    description: Twitch User is Live!
    mode: restart
    trigger:
    - platform: state
      entity_id:
        - sensor.twitch_drzzs
        - sensor.twitch_jfavignano
        - sensor.twitch_jefffavignano_live
        - sensor.twitch_ttthefineprinttt
      to: "streaming"
      for: 00:00:01
#    - platform: state
#      entity_id: sensor.twitch_hayliekyu
#      to: 'streaming'
#      for: 00:00:01
    condition:
      - condition: state
        entity_id: person.wayne
        state: 'home'
      - condition: state
        entity_id: input_boolean.sleeping
        state: 'off'
      - condition: state
        entity_id: input_boolean.twitch_alerts
        state: 'on'
    action:
      - service: button.press
        data: {}
        target:
          entity_id: button.test_light_living_room_61bc3603_identify
      - service: persistent_notification.create
        data:
          notification_id: twitch_stream
          title: Twitch Stream
          message: Greeting, {{ trigger.to_state.attributes.friendly_name }} is streaming live on Twitch https://www.twitch.tv/{{ trigger.to_state.attributes.friendly_name }}/"
      - service: notify.parents_living_room_tv
        data:
          message: "Greetings, {{ trigger.to_state.attributes.friendly_name }} is streaming live on Twitch"
      - service: tts.google_say
        data:
          entity_id: media_player.house_speakers
          message: Twitch Streamer,  {{ trigger.to_state.attributes.friendly_name }} started streaming at {{now().strftime("%m/%d/%Y %H:%M %p")}}.
