---
#########################################################################################################
# Twitch Integration
# GitHub: @waynethebrain/home-assistant-config/
# Version: 3.6522.2
# OP:https://github.com/happyleavesaoc/my-home-automation/blob/master/homeassistant/packages/twitch.yaml
# Description: Monitor Twitch streamer activity on twitch.tv.
# Notes: Twitch Purple Hex Color Code: #9146FF
# Latest Error: None - 6/5/2022 6:00PM
#########################################################################################################

sensor:
  platform: twitch
  entity_namespace: twitch
  client_id: !secret twitch_api
  client_secret: !secret twitch_api_secret
  token: !secret twitch_token
  channels:
    - !secret twitch1
    - !secret twitch2
    - !secret twitch7
group:
  Twitch Users:
    - sensor.twitch_twitch1
    - sensor.twitch_twitch2
    - sensor.twitch_twitch7
    - weblink.twitch
    - input_boolean.twitch_alerts

automation:
  # Streamer online notifications.
  - alias: Entertainment // Twitch / Twitch User Live Notification
    id: twitch-user-streaming-automation
    description: Twitch User is Live!
    mode: restart
    trigger:
      platform: state
      entity_id:
        - sensor.twitch_twitch1
        - sensor.twitch_twitch2
        - sensor.twitch_twitch7
      to: 'streaming'
      for: 00:00:60
    condition:
      - condition: state
        entity_id: person.wayne
        state: 'home'
      - condition: state
        entity_id: input_boolean.sleeping
        state: 'off'
      - condition: state
        entity_id: input_boolean.twitch_alerts
        state: 'on'
    action:
      - service: persistent_notification.create
        data:
          notification_id: twitch_stream
          title: twitch stream
          message: >
              '{{ trigger.to_state.attributes.friendly_name }} is streaming live on Twitch https://www.twitch.tv/{{ trigger.to_state.attributes.friendly_name }}/"
#      - service: notify.parents_living_room_tv
#        data_template:
#          message: >
#            '{{ trigger.to_state.attributes.friendly_name }} is streaming live on Twitch'
#      - service: notify.twitter
#        data_template:
#          message: >
#            {{ trigger.to_state.attributes.friendly_name }} is streaming live on Twitch   https://www.twitch.tv/{{ trigger.to_state.attributes.friendly_name }}/
      - service: notify.parents_living_room_tv
        data_template:
          message: >
            {{ trigger.to_state.attributes.friendly_name }} is streaming live on Twitch
