#################################################
# Alarm Control
################################################# 
alarm_control_panel:
  - platform: manual
    name: Sentry Guard
    code: !secret alarm_code
    trigger_time: 3600
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
    armed_away:
      arming_time: !secret away_arming_time
      delay_time: 0
    armed_night:
      arming_time: !secret night_arming_time
      delay_time: 0


automation:
  - id: 'b39f83b7-2d5c-49fb-83d2-f69aebdd4d72'
    alias: Sentry Guard - Automation
    description: 'Intrusion Detection with Choose Functionality'
    trigger:
    - platform: state
      entity_id: input_boolean.demo_virtual_doorsensor
      to: 'on'
      id: Demo Virtual Doorsensor
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: TRIGGER_ALARM
      id: Trigger Alarm (Actionable Notification)
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: DISARM_ALARM
      id: Disarm Alarm (Actionable Notification)
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: PANIC_ALARM
      id: Panic Alarm (Actionable Notification)
    - platform: state
      entity_id: alarm_control_panel.sentry
      to: disarmed
      id: Disarm Alarm (Auto)
    condition: []
    action: 
    - service: notify.mobile_app_waynes_ipad
      data:
        title: Sentry Guard has been Activated!
        message: An intrusion has been detected .
        data:
          actions:
          - action: TRIGGER_ALARM
            title: Trigger Alarmp
            destructive: true
            authenticationRequired: false
          - action: DISARM_ALARM
            title: Disarm Alarm
            destructive: false
            authenticationRequired: false
          - action: PANIC_ALARM
            title: Activate Panic Alarm
            destructive: true
            authenticationRequired: true
    - choose:
        - conditions:
          - condition: trigger
            id: Demo Virtual Doorsensor
          - condition: or
            conditions:
              - condition: state
                entity_id: alarm_control_panel.sentry
                state: armed_home
              - condition: state
                entity_id: alarm_control_panel.sentry
                state: armed_away
              - condition: state
                entity_id: alarm_control_panel.sentry
                state: armed_night
          sequence:
          - service: alarm_control_panel.alarm_trigger
            target:
              entity_id: alarm_control_panel.sentry
          - service: tts.google_say
            data:
              entity_id: media_player.house_speakers
              message: Alarm triggered via Automation
          - service: persistent_notification.create
            data:
              notification_id: intrusion_alarm
              message: Alarm triggered via Automation
              title: Alarm via Automation
        - conditions:
          - condition: trigger
            id: Trigger Alarm (Actionable Notification)
          sequence:
          - service: tts.google_say
            data:
              entity_id: media_player.house_speakers
              message: Alarm triggered manually via an actionable notification
          - service: persistent_notification.create
            data:
              notification_id: intrusion_alarm
              title: Alarm triggered via Actionable Notification
              message: Alarm triggered manually via an actionable notification
        - conditions:
          - condition: trigger
            id: Panic Alarm (Actionable Notification)
          sequence:
          - service: tts.google_say
            data:
              entity_id: media_player.house_speakers
              message: Silent Alarm Triggered via Actionable Notification
          - service: persistent_notification.create
            data:
              notification_id: intrusion_alarm
              title: Panic Alarm Triggered
              message: Panic Alarm Triggered
        - conditions:
          - condition: trigger
            id: Disarm Alarm (Actionable Notification)
          sequence:
          - service: alarm_control_panel.alarm_disarm
            data:
              code: !secret alarm_code
            target:
              entity_id: alarm_control_panel.sentry
          - service: persistent_notification.create
            data:
              notification_id: intrusion_alarm
              title: Alarm disarmed via actionable notification
              message: Alarm disarmed via actionable notifications
          - service: tts.google_say
            data:
              entity_id: media_player.house_speakers
              message: Alarm disarmed via Actionable Notification
        - conditions:
          - condition: trigger
            id: Disarm Alarm (Auto)
          sequence:
          - service: alarm_control_panel.alarm_disarm
            target:
              entity_id: alarm_control_panel.sentry
            data:
              code: !secret alarm_code
          - service: tts.google_say
            data:
              entity_id: media_player.house_speakers
              message: Alarm disarmed via automation
          - service: persistent_notification.create
            data:
              notification_id: intrusion_alarm
              title: Alarm disarmed via automation
              message: Alarm disarmed via automation
      default: []
    mode: queued
