---
###################################################################################################
# Nightlight Automation
# GitHub: @waynethebrain
# Nightlight automations using motion & open/close sensors with the choose, sequence and repeat functions.
# 
###################################################################################################



group:
  nightlights:
    entities:
      - light.test_light_level_on_off
      
#scripts:

automation:
  - id: 'f894468f-73a4-4dd1-bbf6-d44178645c42'
    alias: Nightlight Test Automation
    description: 'Automatically turn on night lights depending on motion detector that was triggered condition on state of sun aka sunrise or sunset'
    trigger:
    - platform: sun
      event: sunset
      id: Sunset
      offset: '-01:00:00'
    - platform: state
      entity_id: input_boolean.demo_virtual_motionsensor
      for: '00:00:01'
      id: Virtual Motion Detector - ON
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_boolean.demo_virtual_motionsensor
      id: Virtual Motion Detector - OFF
      from: 'on'
      to: 'off'
      for: '00:00:05'
    condition: []
    action:
    - choose:
        #Codition 0 
        - conditions:
            - condition: trigger
              id: Virtual Motion Detector - ON
#            - condition: trigger
#              id: Sunset
          sequence:
            - repeat:
                until:
                ##Wouldn't work using the Trigger ID, therefore changed to the full event state code##
                  - condition: state
                    entity_id: input_boolean.demo_virtual_motionsensor
                    state: 'off'
                    for:
                      hours: 0
                      minutes: 0
                      seconds: 5
                      milliseconds: 0
                sequence:
                  - type: turn_on
                    device_id: 48713c969ec8bdbb02c7ee3f2aaca6e1
                    entity_id: light.test_light_level_on_off
                    domain: light
                    brightness_pct: 20
                  - delay:
                      hours: 0
                      minutes: 5
                      seconds: 0
                      milliseconds: 0  
                  - type: turn_off
                    device_id: 48713c969ec8bdbb02c7ee3f2aaca6e1
                    entity_id: light.test_light_level_on_off
                    domain: light
        #Codition 1
        # - conditions: []
        #   sequence: []
###################################################################################################
#Codition 0 - Template 
###################################################################################################
        - conditions:
            - condition: trigger
              id: Virtual Motion Detector - ON
#            - condition: trigger
#              id: Sunset
          sequence:
            - repeat:
                until:
                ##Wouldn't work using the Trigger ID, therefore changed to the full event state code##
                  - condition: state
                    entity_id: input_boolean.demo_virtual_motionsensor
                    state: 'off'
                    for:
                      hours: 0
                      minutes: 0
                      seconds: 5
                      milliseconds: 0
                sequence:
                  - type: turn_on
                    device_id: 48713c969ec8bdbb02c7ee3f2aaca6e1
                    entity_id: light.test_light_level_on_off
                    domain: light
                    brightness_pct: 20
                  - delay:
                      hours: 0
                      minutes: 5
                      seconds: 0
                      milliseconds: 0  
                  - type: turn_off
                    device_id: 48713c969ec8bdbb02c7ee3f2aaca6e1
                    entity_id: light.test_light_level_on_off
                    domain: light
    mode: parallel
    max: 20
